"use client";
import {useEffect,useState} from "react";
import {binanceSymbol} from "../../lib/market-data";

type Book={bids:[string,string][];asks:[string,string][]};
export default function FuturesMarketData({pair}:{pair:string}){
 const [book,setBook]=useState<Book>({bids:[],asks:[]});const [trades,setTrades]=useState<any[]>([]);const [ticker,setTicker]=useState<any>({});
 useEffect(()=>{let stop=false;const symbol=binanceSymbol(pair);const load=async()=>{try{const [d,t,k]=await Promise.all([fetch(`/api/market/futures?type=depth&symbol=${symbol}`).then(r=>r.json()),fetch(`/api/market/futures?type=trades&symbol=${symbol}`).then(r=>r.json()),fetch(`/api/market/futures?type=ticker&symbol=${symbol}`).then(r=>r.json())]);if(!stop){setBook({bids:d.bids||[],asks:d.asks||[]});setTrades(t||[]);setTicker(k||{})}}catch{}};load();const id=setInterval(load,3000);return()=>{stop=true;clearInterval(id)}},[pair]);
 return <div className="futures-data-grid"><section className="panel market-data-panel"><div className="section-heading"><div><div className="label">MARKET DEPTH</div><h2>Order book</h2></div><span className="muted tiny">Live</span></div><div className="book-head"><span>Price (USDT)</span><span>Amount</span></div><div className="book-side asks">{book.asks.slice(0,6).reverse().map((x,i)=><div key={i}><span>{Number(x[0]).toFixed(2)}</span><span>{Number(x[1]).toFixed(4)}</span></div>)}</div><div className="book-mid">Spread {book.asks[0]&&book.bids[0]?((+book.asks[0][0])-(+book.bids[0][0])).toFixed(2):"—"}</div><div className="book-side bids">{book.bids.slice(0,6).map((x,i)=><div key={i}><span>{Number(x[0]).toFixed(2)}</span><span>{Number(x[1]).toFixed(4)}</span></div>)}</div></section><section className="panel market-data-panel"><div className="section-heading"><div><div className="label">RECENT ACTIVITY</div><h2>Recent trades</h2></div><span className="muted tiny">24h {ticker.priceChangePercent?`${Number(ticker.priceChangePercent).toFixed(2)}%`:"—"}</span></div><div className="trades-head"><span>Price</span><span>Quantity</span><span>Time</span></div>{trades.slice(0,10).map((t,i)=><div className={`trade-line ${t.isBuyerMaker?"down":"up"}`} key={i}><span>{Number(t.p).toFixed(2)}</span><span>{Number(t.q).toFixed(4)}</span><span>{new Date(t.T||Date.now()).toLocaleTimeString()}</span></div>)}</section></div>
}
