"use client";

import {useEffect,useRef,useState} from "react";
import {binanceSymbol,formatPrice} from "../../lib/market-data";

type ChartInterval="1m"|"15m"|"1h"|"4h"|"1d";
type Candle={time:number;open:number;high:number;low:number;close:number;volume:number};
const intervals:Record<ChartInterval,string>={"1m":"1m","15m":"15m","1h":"1h","4h":"4h","1d":"1d"};

export default function OrbitexMarketChart({pair}:{pair:string}){
  const canvasRef=useRef<HTMLCanvasElement|null>(null);const wrapRef=useRef<HTMLDivElement|null>(null);
  const [interval,setInterval]=useState<ChartInterval>("1m");const [candles,setCandles]=useState<Candle[]>([]);const [hover,setHover]=useState<number|null>(null);const symbol=binanceSymbol(pair);
  useEffect(()=>{let alive=true;let socket:WebSocket|undefined;
    fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${intervals[interval]}&limit=220`,{cache:"no-store"}).then(r=>r.json()).then(rows=>{if(!alive||!Array.isArray(rows))return;setCandles(rows.map((r:any)=>({time:+r[0],open:+r[1],high:+r[2],low:+r[3],close:+r[4],volume:+r[5]})))}).catch(()=>{});
    try{socket=new WebSocket(`wss://stream.binance.com:9443/ws/${symbol.toLowerCase()}@kline_${intervals[interval]}`);socket.onmessage=e=>{try{const k=JSON.parse(e.data)?.k;if(!k||!alive)return;const next={time:+k.t,open:+k.o,high:+k.h,low:+k.l,close:+k.c,volume:+k.v};setCandles(c=>{const a=c.slice();const i=a.findIndex(x=>x.time===next.time);if(i>=0)a[i]=next;else a.push(next);return a.slice(-220)})}catch{}}}catch{}
    return()=>{alive=false;socket?.close()};
  },[symbol,interval]);
  useEffect(()=>{const canvas=canvasRef.current,wrap=wrapRef.current;if(!canvas||!wrap)return;const draw=()=>{const r=wrap.getBoundingClientRect(),d=window.devicePixelRatio||1;canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);const ctx=canvas.getContext("2d");if(!ctx)return;ctx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height;ctx.fillStyle="#070b11";ctx.fillRect(0,0,w,h);if(candles.length<2){ctx.fillStyle="#718096";ctx.font="13px system-ui";ctx.fillText("Loading chart data…",18,28);return}const left=10,right=68,top=14,bottom=34,volH=Math.max(58,h*.18),chartH=h-top-bottom-volH,v=candles.slice(-120),hi=Math.max(...v.map(c=>c.high)),lo=Math.min(...v.map(c=>c.low)),pad=(hi-lo)*.06||hi*.001,max=hi+pad,min=lo-pad,step=(w-left-right)/v.length,bw=Math.max(2,Math.min(10,step*.62)),y=(p:number)=>top+(max-p)/(max-min)*chartH;
    ctx.strokeStyle="#18202b";ctx.lineWidth=1;for(let i=0;i<=6;i++){const gy=top+chartH*i/6;ctx.beginPath();ctx.moveTo(left,gy+.5);ctx.lineTo(w-right,gy+.5);ctx.stroke()}for(let i=0;i<=8;i++){const gx=left+(w-left-right)*i/8;ctx.beginPath();ctx.moveTo(gx+.5,top);ctx.lineTo(gx+.5,top+chartH);ctx.stroke()}
    const maxVol=Math.max(...v.map(c=>c.volume))||1;v.forEach((c,i)=>{const x=left+i*step+step/2,up=c.close>=c.open;ctx.strokeStyle=up?"#20d9a0":"#ef4d68";ctx.beginPath();ctx.moveTo(x,y(c.high));ctx.lineTo(x,y(c.low));ctx.stroke();const a=y(c.open),b=y(c.close);ctx.fillStyle=up?"#20d9a0":"#ef4d68";ctx.fillRect(x-bw/2,Math.min(a,b),bw,Math.max(1,Math.abs(a-b)));ctx.globalAlpha=.3;ctx.fillRect(x-bw/2,top+chartH+volH-(c.volume/maxVol)*volH*.86,bw,(c.volume/maxVol)*volH*.86);ctx.globalAlpha=1});
    const last=v[v.length-1],ly=y(last.close);ctx.strokeStyle=last.close>=last.open?"#20d9a0":"#ef4d68";ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(left,ly);ctx.lineTo(w-right,ly);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=last.close>=last.open?"#20d9a0":"#ef4d68";ctx.fillRect(w-right+3,ly-10,right-8,20);ctx.fillStyle="#06100d";ctx.font="600 11px system-ui";ctx.textAlign="center";ctx.fillText(formatPrice(last.close),w-right/2+3,ly+4);ctx.textAlign="left";ctx.fillStyle="#718096";ctx.font="11px system-ui";ctx.fillText("VOL",left,top+chartH+18);ctx.textAlign="right";for(let i=0;i<=6;i++)ctx.fillText(formatPrice(max-(max-min)*i/6),w-8,top+chartH*i/6+4);ctx.textAlign="left";
    if(hover!==null&&v[hover]){const x=left+hover*step+step/2,c=v[hover];ctx.strokeStyle="#657489";ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+chartH);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#dce5f0";ctx.font="11px system-ui";ctx.fillText(`O ${formatPrice(c.open)}   H ${formatPrice(c.high)}   L ${formatPrice(c.low)}   C ${formatPrice(c.close)}`,left+8,top+12)}
  };draw();const ro=new ResizeObserver(draw);ro.observe(wrap);return()=>ro.disconnect()},[candles,hover]);
  function pointer(e:React.PointerEvent<HTMLCanvasElement>){const c=canvasRef.current;if(!c||candles.length<2)return;const r=c.getBoundingClientRect(),left=10,right=68,step=(r.width-left-right)/Math.min(120,candles.length),i=Math.max(0,Math.min(Math.min(120,candles.length)-1,Math.floor((e.clientX-r.left-left)/step)));setHover(i)}
  return <div className="chart live-chart custom-market-chart" ref={wrapRef}><div className="chart-toolbar custom-chart-toolbar"><div className="chart-intervals">{(Object.keys(intervals) as ChartInterval[]).map(x=><button key={x} className={interval===x?"active":""} onClick={()=>setInterval(x)}>{x}</button>)}</div><div className="chart-tools"><span>⌁</span><span>＋</span><span>−</span><span>⌖</span></div><strong>{pair}</strong><span className="chart-source">Orbitex Chart</span></div><div className="custom-chart-canvas-wrap"><canvas ref={canvasRef} onPointerMove={pointer} onPointerLeave={()=>setHover(null)}/></div></div>;
}
