import type { Express, RequestHandler } from 'express';
import { createClient } from '@supabase/supabase-js';
import { deriveBitcoinDepositAddress, scanBitcoinDeposit, bitcoinTipHeight, buildBitcoinSweep, broadcastBitcoinSweep } from './bitcoin-adapter.js';
import { registerSolanaRoutes } from './solana-routes.js';

function validateUserId(userId: string) { return /^[0-9a-f-]{36}$/i.test(userId); }

export function registerBitcoinRoutes(app: Express, authorized: RequestHandler) {
  const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false, autoRefreshToken: false } });
  const confirmationsRequired = Number(process.env.BITCOIN_CONFIRMATIONS_REQUIRED || process.env.CONFIRMATIONS_REQUIRED || 3);
  async function allocateBitcoinIndex(userId: string) { const existing = await supabase.from('wallet_accounts').select('derivation_index').eq('user_id', userId).eq('chain_family', 'bitcoin').not('derivation_index', 'is', null).limit(1).maybeSingle(); if (existing.error) throw new Error(existing.error.message); if (existing.data?.derivation_index !== null && existing.data?.derivation_index !== undefined) return Number(existing.data.derivation_index); const allocated = await supabase.rpc('allocate_wallet_derivation_index'); if (allocated.error) throw new Error(`Unable to allocate wallet index: ${allocated.error.message}`); return Number(allocated.data); }
  app.post('/provision-bitcoin/:userId', authorized, async (req, res) => { const userId=String(req.params.userId); if(!validateUserId(userId))return res.status(400).json({error:'Invalid user id'}); if(!process.env.BITCOIN_XPUB?.trim())return res.status(503).json({error:'Bitcoin provisioning is not configured. Set BITCOIN_XPUB.'}); try{const existing=await supabase.from('wallet_accounts').select('*').eq('user_id',userId).eq('asset','BTC').eq('network','bitcoin').maybeSingle();if(existing.error)return res.status(500).json({error:existing.error.message});if(existing.data)return res.json({ok:true,wallet:existing.data,created:false});const index=await allocateBitcoinIndex(userId),derived=deriveBitcoinDepositAddress(index),inserted=await supabase.from('wallet_accounts').insert({user_id:userId,asset:'BTC',network:'bitcoin',chain_family:'bitcoin',deposit_address:derived.address,derivation_index:index,status:'active'}).select('*').single();if(inserted.error)return res.status(500).json({error:inserted.error.message});return res.status(201).json({ok:true,wallet:inserted.data,created:true});}catch(error){return res.status(500).json({error:error instanceof Error?error.message:'Unable to provision Bitcoin wallet'});}});
  app.post('/verify-bitcoin-deposit', authorized, async (req, res) => { const userId=String(req.body?.userId||''),txHash=String(req.body?.txHash||'').trim().toLowerCase(),submittedAmount=String(req.body?.amount||'').trim();if(!validateUserId(userId))return res.status(400).json({error:'Invalid user id'});if(!/^[a-f0-9]{64}$/.test(txHash))return res.status(400).json({error:'Invalid Bitcoin transaction id'});if(!/^\d+(\.\d{1,8})?$/.test(submittedAmount)||Number(submittedAmount)<=0)return res.status(400).json({error:'Invalid BTC amount'});try{const account=await supabase.from('wallet_accounts').select('id,deposit_address').eq('user_id',userId).eq('asset','BTC').eq('network','bitcoin').maybeSingle();if(account.error)return res.status(500).json({error:account.error.message});if(!account.data?.deposit_address)return res.status(400).json({error:'Your BTC deposit address has not been provisioned yet.'});const existing=await supabase.from('wallet_deposits').select('id,status,user_id').eq('network','bitcoin').eq('asset','BTC').eq('tx_hash',txHash).maybeSingle();if(existing.error)return res.status(500).json({error:existing.error.message});if(existing.data)return res.status(409).json({error:'This transaction has already been submitted.',deposit:existing.data});const utxos=await scanBitcoinDeposit(account.data.deposit_address,0),matches=utxos.filter(u=>u.txid.toLowerCase()===txHash);if(!matches.length)return res.status(400).json({error:'No unspent BTC output from this transaction was found at your deposit address.'});const amountSats=matches.reduce((sum,u)=>sum+u.valueSats,0n),expectedSats=BigInt(Math.round(Number(submittedAmount)*100000000));if(amountSats!==expectedSats)return res.status(400).json({error:`Amount mismatch. On-chain amount is ${(Number(amountSats)/100000000).toFixed(8)} BTC.`});const tipHeight=await bitcoinTipHeight(),oldestMatchHeight=Math.min(...matches.map(u=>u.height)),confirmations=Math.max(0,tipHeight-oldestMatchHeight+1),status=confirmations>=confirmationsRequired?'credited':'confirming';const inserted=await supabase.rpc('record_verified_wallet_deposit',{p_user_id:userId,p_wallet_account_id:account.data.id,p_asset:'BTC',p_network:'bitcoin',p_chain_family:'bitcoin',p_tx_hash:txHash,p_from_address:'',p_to_address:account.data.deposit_address,p_amount:(Number(amountSats)/100000000).toFixed(8),p_confirmations:confirmations,p_status:status,p_credited_at:status==='credited'?new Date().toISOString():null});if(inserted.error){if(inserted.error.code==='23505')return res.status(409).json({error:'This transaction has already been submitted.'});return res.status(500).json({error:inserted.error.message});}return res.status(201).json({ok:true,status,confirmations,requiredConfirmations:confirmationsRequired,deposit:inserted.data});}catch(error){return res.status(400).json({error:error instanceof Error?error.message:'Unable to verify Bitcoin transaction'});}});
  app.post('/admin/sweep/bitcoin/:walletAccountId', authorized, async (req,res)=>{if(process.env.SWEEP_ENABLED!=='true')return res.status(503).json({error:'Sweep worker is disabled.'});if(!process.env.BITCOIN_XPRV?.trim()||!process.env.BITCOIN_TREASURY_ADDRESS?.trim())return res.status(503).json({error:'Bitcoin sweeping is not configured. Set BITCOIN_XPRV and BITCOIN_TREASURY_ADDRESS.'});try{const account=await supabase.from('wallet_accounts').select('id,asset,network,deposit_address,derivation_index,status').eq('id',String(req.params.walletAccountId)).maybeSingle();if(account.error)throw new Error(account.error.message);if(!account.data||account.data.asset!=='BTC'||account.data.network!=='bitcoin'||account.data.status!=='active'||account.data.derivation_index===null)throw new Error('BTC wallet account is not ready for sweeping.');const utxos=await scanBitcoinDeposit(account.data.deposit_address,confirmationsRequired);if(!utxos.length)return res.json({ok:true,status:'nothing_to_sweep'});const built=await buildBitcoinSweep({index:Number(account.data.derivation_index),treasuryAddress:process.env.BITCOIN_TREASURY_ADDRESS.trim(),utxos}),txid=await broadcastBitcoinSweep(built.txHex);return res.json({ok:true,status:'broadcast',txid,amountSats:built.amountSats.toString(),feeSats:built.feeSats.toString(),feeRateSatVb:built.feeRateSatVb});}catch(error){return res.status(400).json({error:error instanceof Error?error.message:'Unable to sweep Bitcoin wallet.'});}});
  registerSolanaRoutes(app, authorized);
}
