import { Connection, Keypair, PublicKey, SystemProgram, Transaction, sendAndConfirmTransaction } from '@solana/web3.js';
import { getAssociatedTokenAddress, getOrCreateAssociatedTokenAccount, createTransferInstruction } from '@solana/spl-token';
import { mnemonicToSeedSync } from 'bip39';
import { derivePath } from 'ed25519-hd-key';

function rpcUrl() { const url=process.env.SOLANA_RPC_URL?.trim(); if(!url) throw new Error('SOLANA_RPC_URL is not configured.'); return url; }
export function connection(){ return new Connection(rpcUrl(),'confirmed'); }
function mnemonic(){ const value=process.env.SOLANA_MNEMONIC?.trim(); if(!value) throw new Error('SOLANA_MNEMONIC is not configured.'); return value; }
export function deriveSolanaDeposit(index:number){ if(!Number.isInteger(index)||index<0) throw new Error('Invalid Solana derivation index.'); const seed=mnemonicToSeedSync(mnemonic()); const derived=derivePath(`m/44'/501'/${index}'/0'`,seed.toString('hex')).key; const keypair=Keypair.fromSeed(Buffer.from(derived)); return {index,address:keypair.publicKey.toBase58(),keypair}; }
export function treasuryKeypair(){ const value=process.env.SOLANA_TREASURY_PRIVATE_KEY?.trim(); if(!value) throw new Error('SOLANA_TREASURY_PRIVATE_KEY is not configured.'); try { return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(value))); } catch { throw new Error('SOLANA_TREASURY_PRIVATE_KEY must be a JSON secret-key array.'); } }
export function configuredSplMint(asset:string){ const raw=process.env.SOLANA_SPL_TOKEN_CONTRACTS_JSON?.trim(); if(!raw) return null; const parsed=JSON.parse(raw) as Record<string,string>; const mint=parsed[asset.toUpperCase()]; return mint?new PublicKey(mint):null; }
async function feeFor(conn:Connection,tx:Transaction){ return (await conn.getFeeForMessage(tx.compileMessage(),'confirmed')).value??5000; }
export async function sweepSolanaNative(index:number,treasuryAddress:string){ const conn=connection(),source=deriveSolanaDeposit(index),treasury=new PublicKey(treasuryAddress); const balance=await conn.getBalance(source.keypair.publicKey,'confirmed'); if(balance<=0)return null; const latest=await conn.getLatestBlockhash('confirmed'); const probe=new Transaction({recentBlockhash:latest.blockhash,feePayer:source.keypair.publicKey}).add(SystemProgram.transfer({fromPubkey:source.keypair.publicKey,toPubkey:treasury,lamports:1})); const fee=await feeFor(conn,probe); if(balance<=fee)return null; const tx=new Transaction({recentBlockhash:latest.blockhash,feePayer:source.keypair.publicKey}).add(SystemProgram.transfer({fromPubkey:source.keypair.publicKey,toPubkey:treasury,lamports:balance-fee})); const signature=await sendAndConfirmTransaction(conn,tx,[source.keypair],{commitment:'confirmed'}); return {signature,lamports:balance-fee,feeLamports:fee}; }
export async function sweepSolanaSpl(index:number,mintAddress:string,treasuryAddress:string){ const conn=connection(),source=deriveSolanaDeposit(index),treasury=treasuryKeypair(),mint=new PublicKey(mintAddress),treasuryOwner=new PublicKey(treasuryAddress); const sourceAta=await getAssociatedTokenAddress(mint,source.keypair.publicKey); const sourceInfo=await conn.getTokenAccountBalance(sourceAta,'confirmed'); const raw=BigInt(sourceInfo.value.amount); if(raw<=0n)return null; const treasuryAta=await getOrCreateAssociatedTokenAccount(conn,treasury,mint,treasuryOwner,true); const latest=await conn.getLatestBlockhash('confirmed'); const tx=new Transaction({recentBlockhash:latest.blockhash,feePayer:source.keypair.publicKey}).add(createTransferInstruction(sourceAta,treasuryAta.address,source.keypair.publicKey,raw)); const fee=await feeFor(conn,tx); const native=await conn.getBalance(source.keypair.publicKey,'confirmed'); if(native<fee){ const needed=fee-native; const treasuryBalance=await conn.getBalance(treasury.publicKey,'confirmed'); if(treasuryBalance<needed) throw new Error('Solana treasury does not have enough SOL to fund sweep gas.'); const fundingBlockhash=await conn.getLatestBlockhash('confirmed'); const funding=new Transaction({recentBlockhash:fundingBlockhash.blockhash,feePayer:treasury.publicKey}).add(SystemProgram.transfer({fromPubkey:treasury.publicKey,toPubkey:source.keypair.publicKey,lamports:needed})); await sendAndConfirmTransaction(conn,funding,[treasury],{commitment:'confirmed'}); } const finalBlockhash=await conn.getLatestBlockhash('confirmed'); tx.recentBlockhash=finalBlockhash.blockhash; const signature=await sendAndConfirmTransaction(conn,tx,[source.keypair],{commitment:'confirmed'}); return {signature,amount:raw,feeLamports:fee}; }
export async function getSolanaTokenBalance(address:string,mintAddress:string){ const conn=connection(),owner=new PublicKey(address),mint=new PublicKey(mintAddress); const accounts=await conn.getParsedTokenAccountsByOwner(owner,{mint},{commitment:'confirmed'}); return accounts.value.reduce((sum,a)=>sum+BigInt(a.account.data.parsed.info.tokenAmount.amount),0n); }
