"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {getTestnetOrders,getTestnetPositions} from "../../lib/testnet-store";
import type {StoredOrder,StoredPosition} from "../../lib/testnet-store";
export default function Orders(){
  const [tab,setTab]=useState("Order history");
  const [orders,setOrders]=useState<StoredOrder[]>([]);
  const [positions,setPositions]=useState<StoredPosition[]>([]);
  function refresh(){setOrders(getTestnetOrders());setPositions(getTestnetPositions())}
  useEffect(()=>{refresh()},[]);
  return <main className="app-shell"><header className="appbar"><Link className="brand" href="/">ARBITRAGE<span>.</span></Link><nav><Link href="/dashboard">Dashboard</Link><Link href="/trade">Spot</Link><Link href="/futures">Futures</Link><Link href="/wallet">Wallet</Link><Link className="active" href="/orders">Orders</Link></nav><Link className="btn" href="/">Account</Link></header><section className="app-content"><div className="page-title"><div><div className="eyebrow">TESTNET ACTIVITY</div><h1>Orders & positions</h1></div><button className="btn" onClick={refresh}>Refresh</button></div><div className="panel"><div className="tabs static">{["Open orders","Order history","Trade history","Positions"].map(t=><button key={t} className={tab===t?"on":""} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==="Positions"?<div>{positions.length===0?<div className="empty"><div className="empty-icon">—</div><h2>No testnet positions</h2><p className="muted">Positions created on the Futures page will appear here.</p><Link className="btn primary" href="/futures">Open futures</Link></div>:<div className="market-list">{positions.map(p=><div className="panel" key={p.id}><div className="trade-head"><div><div className="pair">{p.symbol} · {p.side}</div><div className="muted">Entry {p.entryPrice.toFixed(2)} · Mark {p.markPrice.toFixed(2)}</div></div><strong>{p.leverage}x</strong></div><div className="order-info"><span>Quantity</span><span>{p.quantity}</span><span>Margin</span><span>{p.margin.toFixed(2)} USDT</span></div><div className="order-info"><span>Unrealized P&amp;L</span><strong>{p.unrealizedPnl.toFixed(2)} USDT</strong><span>Status</span><span>{p.status||"OPEN"}</span></div><div className="order-info"><span>Take profit</span><span>{p.takeProfit?.toFixed(2)||"—"}</span><span>Stop loss</span><span>{p.stopLoss?.toFixed(2)||"—"}</span></div><div className="order-info"><span>Est. liquidation</span><span>{p.liquidationPrice.toFixed(2)}</span></div></div>)}</div>}</div>:<div>{orders.length===0?<div className="empty"><div className="empty-icon">—</div><h2>{tab==="Open orders"?"No open orders":"No testnet order history"}</h2><p className="muted">{tab==="Open orders"?"The current testnet API fills spot orders immediately.":"Spot testnet orders will appear here after submission."}</p><Link className="btn primary" href="/trade">Start trading</Link></div>:<div className="market-list">{orders.map(o=><div className="panel" key={o.id}><div className="trade-head"><div><div className="pair">{o.symbol} · {o.side}</div><div className="muted">{new Date(o.createdAt).toLocaleString()}</div></div><span className="up">{o.status}</span></div><div className="order-info"><span>Type</span><span>{o.type}</span><span>Price</span><span>{o.price.toFixed(2)}</span><span>Quantity</span><span>{o.quantity}</span></div></div>)}</div>}</div>}<p className="muted tiny">Testnet activity is stored only in this browser. No real funds are held or traded.</p></div></section></main>}
