"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import MarketChart from "../components/MarketChart";
import CoinIcon from "../components/CoinIcon";
import {MARKET_SYMBOLS,binanceSymbol,displayPair,formatPrice} from "../../lib/market-data";
import {createSupabaseBrowserClient} from "../../lib/supabase-browser";
const referencePrice=113842.20;

function validPair(value:string|null){
  if(!value)return "BTC/USDT";
  const compact=value.toUpperCase().replace(/[^A-Z0-9]/g,"");
  const matched=MARKET_SYMBOLS.find(symbol=>symbol===compact);
  return matched?displayPair(matched):"BTC/USDT";
}

export default function Trade(){
 const searchParams=useSearchParams();
 const [pair,setPair]=useState(()=>validPair(searchParams.get("pair")));
 const [side,setSide]=useState("Buy");const [type,setType]=useState("Limit");const [price,setPrice]=useState(String(referencePrice));const [livePrice,setLivePrice]=useState(referencePrice);const [change,setChange]=useState(0);const [amount,setAmount]=useState("");const [submitting,setSubmitting]=useState(false);const [message,setMessage]=useState("");const [available,setAvailable]=useState(0);const symbol=binanceSymbol(pair);const base=pair.split("/")[0];

 useEffect(()=>{setPair(validPair(searchParams.get("pair")))},[searchParams]);
 useEffect(()=>{let alive=true;fetch(`https://api.binance.com/api/v3/ticker/24hr?symbol=${symbol}`).then(r=>r.json()).then(r=>{if(alive&&r.lastPrice){const p=Number(r.lastPrice);setLivePrice(p);setPrice(String(p));setChange(Number(r.priceChangePercent||0))}}).catch(()=>{});const ws=new WebSocket(`wss://stream.binance.com:9443/ws/${symbol.toLowerCase()}@ticker`);ws.onmessage=e=>{try{const r=JSON.parse(e.data);if(alive){setLivePrice(Number(r.c));setChange(Number(r.P));}}catch{}};return()=>{alive=false;ws.close()}},[symbol]);
 useEffect(()=>{setPrice(String(livePrice));setMessage("")},[pair]);
 async function refreshBalance(){const supabase=createSupabaseBrowserClient();const {data:{user}}=await supabase.auth.getUser();if(!user){setAvailable(0);return}const {data}=await supabase.from("account_balances").select("available").eq("user_id",user.id).eq("asset","USDT").eq("wallet","SPOT").maybeSingle();setAvailable(Number(data?.available||0))}
 useEffect(()=>{refreshBalance().catch(()=>setAvailable(0))},[]);
 const size=useMemo(()=>{const p=Number(type==="Market"?livePrice:price);const q=Number(amount);return p>0&&q>0?(p*q).toFixed(2):"0.00"},[price,amount,type,livePrice]);
 async function submit(){setMessage("");const orderPrice=type==="Market"?livePrice:Number(price);const quantity=Number(amount);if(!Number.isFinite(orderPrice)||orderPrice<=0||!Number.isFinite(quantity)||quantity<=0){setMessage("Enter a valid price and amount.");return}setSubmitting(true);try{const res=await fetch("/api/testnet/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:pair,side:side.toUpperCase(),type:type.toUpperCase(),price:orderPrice,quantity,clientOrderId:crypto.randomUUID()})});const data=await res.json();if(!res.ok||!data.ok)throw new Error(data.error||"Order rejected");await refreshBalance();setMessage(`Testnet order filled: ${data.order?.side||side.toUpperCase()} ${data.order?.quantity||quantity} ${base} @ ${formatPrice(orderPrice)}`);setAmount("")}catch(error){setMessage(error instanceof Error?error.message:"Order failed")}finally{setSubmitting(false)}}
 return <main className="app-shell"><header className="appbar"><Link className="brand" href="/"><img src="/orbitex-logo.svg" alt="ORBITEX" style={{width:30,height:30,objectFit:"contain"}}/><span>ORBITEX.</span></Link><nav><Link href="/dashboard">Dashboard</Link><Link className="active" href="/trade">Spot</Link><Link href="/futures">Futures</Link><Link href="/wallet">Wallet</Link><Link href="/orders">Orders</Link></nav><Link className="btn" href="/dashboard">Account</Link></header><div className="trade-layout"><aside className="market-list"><div className="label">MARKETS</div>{MARKET_SYMBOLS.map(m=>{const p=displayPair(m),coin=m.replace("USDT","");return <button className={p===pair?"selected":""} onClick={()=>setPair(p)} key={m}><span style={{display:"inline-flex",alignItems:"center",gap:7}}><CoinIcon symbol={coin} size={24}/>{p}</span><small>LIVE</small></button>})}</aside><section className="chart-area"><div className="trade-head"><div><div className="pair">{pair}</div><div className="price">{formatPrice(livePrice)} <span className={change<0?"danger":"up"}>{change>=0?"+":""}{change.toFixed(2)}%</span></div><div className="muted tiny">Live public market price</div></div><Link className="btn" href="/futures">Open Futures</Link></div><MarketChart pair={pair}/></section><section className="order-panel"><div className="tabs"><button className={side==="Buy"?"on":""} onClick={()=>setSide("Buy")}>Buy</button><button className={side==="Sell"?"on":""} onClick={()=>setSide("Sell")}>Sell</button></div><div className="order-types">{["Limit","Market"].map(t=><button className={type===t?"on":""} onClick={()=>setType(t)} key={t}>{t}</button>)}</div><label>Price<input value={type==="Market"?formatPrice(livePrice):price} disabled={type==="Market"} onChange={e=>setPrice(e.target.value)} placeholder="USDT"/></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="0.00"/></label><label>Size<input value={`${size} USDT`} readOnly/></label><div className="order-info"><span>Available</span><span>{available.toFixed(2)} USDT</span></div>{message&&<div className="notice">{message}</div>}<button className="btn primary full" disabled={submitting} onClick={submit}>{submitting?"Submitting…":`${side} ${base}`}</button><p className="muted tiny">Testnet only. Orders are authenticated and settled through the server-side exchange ledger; no real funds are submitted.</p><Link className="muted tiny" href="/orders">View testnet order history →</Link></section></div></main>}
