"use client";

import Link from "next/link";
import { ArrowLeft, Copy, ShieldCheck } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import MobileNav from "../../../components/MobileNav";
import "../../wallet.css";
import "../deposit.css";

const ADDRESSES: Record<string, string> = { bsc: "0x43A690962edb1a5198E856E95fdEE68cFF4F0E83", eth: "0x43A690962edb1a5198E856E95fdEE68cFF4F0E83", arbitrum: "0x43A690962edb1a5198E856E95fdEE68cFF4F0E83", optimism: "0x43A690962edb1a5198E856E95fdEE68cFF4F0E83", polygon: "0x43A690962edb1a5198E856E95fdEE68cFF4F0E83", avalanche: "0x43A690962edb1a5198E856E95fdEE68cFF4F0E83", base: "0x43A690962edb1a5198E856E95fdEE68cFF4F0E83", linea: "0x43A690962edb1a5198E856E95fdEE68cFF4F0E83", tron: "TKqK2iAEKFC7M5RA12gBdskBLGNdtrTH3q3", bitcoin: "bc1q3nu0hklvvnkzfsd6e8g8e29kzd8q9k6mw4ssk2", solana: "79z3yH2t7BcWdSJYx1V9CftpwEDjXS6JryVPTMtLPQJF", aptos: "0x78faf651ee5fab278b1e93e2117bff92bedc182d1077e9d2710a14aedc164fc3", ton: "UQCFeiYwfU9xPr5RkY9-X11HcYLMGPFq766OXZ5a0qyI_9dt", near: "7fb16d6c7600508ff099b67a8b91db5762d835be5d257b0d4cb97af1cd0c909", sui: "0xc7489fba859d9f693e7b9de0de87c919a9b2a2ea8d9fbfb156c4e586f76cb4d5", xrp: "rGvJwEheqLztdxhz32Wgpm1TjPXopUFji", cardano: "addr1q827wexwa8ghk0zknmpllxrk26qvqq9me2e7s69n5shty9hnmevm45jtmst32qsvupk3hepyxkg3ezxzsw06evlelafsp9hksw", dogecoin: "DRYR9UiLC72EEXJMbP86aoCnL149JMLDcM", polkadot: "1nHzS9upAUikrpXCsE1yDHPR7n2r86NL79dHWCH6Wdw6jgc", litecoin: "ltc1qm2s8vkruqyhu9dpneuyct8paky7vemkzzagxur", bitcoincash: "bitcoincash:qpxq2ue80khteuvktl0skfgsm5r78yp7p5r5xsj0st", cosmos: "cosmos146ah07njwh2zyzc54ulwer8c7p3k002jtc6ucc", stellar: "GCWJQUWD2GLEFTR4752RQGHSTRZNP4FUIZUGW74M7SG6F4MUYTDL7AXV" };
const QRS: Record<string, string> = { bsc: "/real_bnb_logo_scannable_qr.png", eth: "/real_eth_logo_scannable_qr.png", tron: "/real_tron_logo_scannable_qr.png", aptos: "/real_aptos_logo_scannable_qr.png", solana: "/real_solana_logo_scannable_qr.png", bitcoin: "/real_btc_logo_scannable_qr.png", arbitrum: "/real_arbitrum_logo_scannable_qr.png", ton: "/real_ton_logo_scannable_qr.png", optimism: "/real_optimism_logo_scannable_qr.png", near: "/real_near_logo_scannable_qr.png", polygon: "/real_polygon_logo_scannable_qr.png", avalanche: "/real_avax_logo_scannable_qr.png", sui: "/real_sui_logo_scannable_qr.png", base: "/real_base_logo_scannable_qr.png", linea: "/real_linea_logo_scannable_qr.png", xrp: "/real_xrp_logo_scannable_qr.png", cardano: "/real_ada_logo_scannable_qr.png", dogecoin: "/real_doge_logo_scannable_qr.png", polkadot: "/real_dot_logo_scannable_qr.png", litecoin: "/real_ltc_logo_scannable_qr.png", bitcoincash: "/real_bch_logo_scannable_qr.png", cosmos: "/real_atom_logo_scannable_qr.png", stellar: "/real_xlm_logo_scannable_qr.png" };

export default function DepositAddressPage() {
  const params = useSearchParams();
  const asset = params.get("asset") || "USDT";
  const assetName = params.get("assetName") || "Tether";
  const network = params.get("network") || "BNB Smart Chain";
  const networkShort = params.get("networkShort") || "BEP-20";
  const networkId = params.get("networkId") || "bsc";
  const address = ADDRESSES[networkId] || "ORBITEX-DEMO-DEPOSIT-ADDRESS";
  const [copied, setCopied] = useState(false);
  async function copyAddress() { try { await navigator.clipboard.writeText(address); } catch {} setCopied(true); window.setTimeout(() => setCopied(false), 1800); }

  return <main className="wallet-page"><header className="wallet-header"><Link href="/wallet" className="wallet-brand"><span className="brand-mark">◉</span> ORBITEX</Link><Link href="/wallet/deposit" className="history-link"><ArrowLeft size={18}/> Back to Deposit</Link></header><div className="wallet-content deposit-content"><div className="wallet-heading"><div><span className="wallet-kicker">FUND YOUR ACCOUNT</span><h1>Deposit address</h1><p>Use this address and QR code for your deposit.</p></div></div><section className="deposit-shell"><div className="deposit-details withdraw-form mobile-visible"><div className="selected-asset-heading"><div className="deposit-asset-logo"><span>{asset.slice(0, 2)}</span></div><div><span className="wallet-kicker">DEPOSIT ASSET</span><h2>{assetName} <em>{asset}</em></h2></div></div><div className="deposit-address-step"><div className="deposit-address-title"><span className="wallet-kicker">YOUR DEPOSIT ADDRESS</span><h3>{asset} on {networkShort}</h3><p>Send only <strong>{asset}</strong> using the <strong>{network}</strong> network.</p></div><div className="deposit-qr-placeholder"><img src={QRS[networkId] || QRS.bsc} alt={`${asset} deposit QR code`} /></div><div className="deposit-address-box"><span>{asset} on {network} ({networkShort}) deposit address</span><strong>{address}</strong><button type="button" onClick={copyAddress}><Copy size={17}/> {copied ? "Copied" : "Copy address"}</button></div><div className="deposit-security-note"><ShieldCheck size={18}/><span>Make sure the network is <strong>{networkShort}</strong> before sending funds.</span></div></div><Link href="/wallet/deposit" className="mobile-back-button" style={{display:"flex",marginTop:14}}><ArrowLeft size={17}/> Choose another asset</Link></div></section></div><MobileNav/></main>;
}
